title:            SelfStore 博客
description:      为数字创作者提供易用的收款和送达服务。
url:              # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          SelfStore
disqus_shortname: selfstore
google_analytics_id: UA-56329871-2

links:
  - name:         SelfStore
    url:          https://selfstore.io/
  - name:         关于
    url:          https://selfstore.io/about
  - name:         Feed
    url:          /feed.xml
  - name:         Email
    url:          mailto:support@selfstore.io
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
